import initScrollSuave from './modules/scrollSuave.js';
import initScrollAnima from './modules/scrollAnimacao.js';
import initAccordion from './modules/accordion.js';
import initTab from './modules/animacaoTab.js';
import initModal from './modules/modal.js';
import initToolTip from './modules/toolTip.js';
import initDropDown from './modules/dropDown.js';
import initMenuMobile from './modules/menuMobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initAnimalsFecth from './modules/animaisFecth.js';
import initBtcFetch from './modules/bitcoinFetch.js';

initScrollSuave();
initScrollAnima();
initAccordion();
initTab();
initModal();
initToolTip();
initDropDown();
initMenuMobile();
initFuncionamento();
initAnimalsFecth();
initBtcFetch();
